name: flutterv1demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.0.0
  cupertino_icons: ^0.1.2
  dio: any
  flutter_screenutil: any
  # NSUserDefault
  shared_preferences: any
  # toast
  fluttertoast: ^2.2.11
  # tuple-dart
  tuple: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/aboutus.png
    - images/cardbox.png
    - images/setting.png
    - images/arrowrright.png
    - images/personcenter_company.png
    - images/personcenter_email.png
    - images/personcenter_phone.png
    - images/personcenter_userno.png
    - images/personcenter_depart.png


