name: hello_flutter1
description: A new Flutter project.
dependencies:
  flutter:
    sdk: flutter
  english_words: ^3.1.3
  cupertino_icons: ^0.1.2
  json_annotation: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
flutter:
  uses-material-design: true
  assets:
    - assets/hello.png
    - assets/hello.txt
